### ISSUE TITLE
求助 新版本发现运行报错

### ISSUE THREAD

**Issue by sunyink** [HaneRo/skland_arknights_checkin#1]
分支为[3edc088](https://github.com/HaneRo/skland_arknights_checkin/commit/3edc0887be9ac4c210372ba339c2e146fbc3379a)。
，环境win py3.8&3.10，旧版本曾成功运行过，
现报错如下：
```
= RESTART: d:\Users\skland_arknights_checkin\skland_arknights_checkin.py
Traceback (most recent call last):
  File "d:\Users\skland_arknights_checkin\skland_arknights_checkin.py", line 139, in <module>
    code=get_code(content)
  File "d:\Users\skland_arknights_checkin\skland_arknights_checkin.py", line 122, in get_code
    raise

RuntimeError: No active exception to reraise
```

打扰，我一点也搞不懂py的报错....

**Comment by HaneRo** [comment]
抱歉忘记更新readme，现在是打开 https://web-api.skland.com/account/info/hg 获取其中content 的值，旧版无法获取计算sign用的token

**Comment by sunyink** [comment]
成了，感谢！！
